Code review: Ruby on Rails Forms
fdfragoso/forms-Ror pull request #1
Opened 2020-09-16 15:12 UTC by fdfragoso

All the requirements from Microverse and The Odin Project were implemented, including the extra credit (show full error messages).

Linter and Rubocop added

Waiting for code review

2020-09-16 16:47 UTC, BrittanyBlake reviewed
### Status: Invalid 🛑 
****
Hi @fdfragoso  and @keddo. This pull request has been marked as invalid because you are missing a [descriptive README](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/). Please ensure that you have a descriptive README file before you submit your next pull request. 

- Additionally, you are missing a master branch. Please note that proper GitFlow means that you should be merging from feature --> development --> master. 

****
Please make the required adjustments and submit a new code review request.

### Good Luck and Happy Coding 🍀 👩🏾‍💻

2020-09-17 10:39 UTC, trekab requested changes
### Changes Required! :recycle: 
Hi @fdfragoso and @keddo! Nice job so far. You have a few changes to make to have this project completed. These are:
- [x] For the `UsersController`, the `update` action should either `redirect_to new_user_path` if the user was saved ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_create.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/forms)) or `render :new` if the user was not saved ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_create.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/forms))
- [x] You were expected to leave the commented out HTML form for this review. This is to justify that you followed the learning steps outlined in the Odin project task. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_form2.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/forms))
- [x] __[Optional]__ Create a partial for the user form and reuse it in both the edit and new view. This would be in line with the [DRY principle](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself).
- [ ] Check out the comments in the code for more feedback.

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__
[GitHub](https://github.com/trekab) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

2020-09-17 10:39 UTC, trekab commented on app/views/users/new.html.erb
> +<% end %>
Using the empty quotes(`""`) in the submit button leaves your submit button without a label.

2020-09-17 10:39 UTC, trekab commented on app/controllers/users_controller.rb
> +    # @user = User.new(username: params[:username], email: params[:email], password: [:password])
Remove this commented code. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

2020-09-17 10:39 UTC, trekab commented on app/controllers/users_controller.rb
> +
Remove this commented code. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

2020-09-17 12:40 UTC, sumancrest0001 approved these changes
**Status: Approved :+1: :1st_place_medal: 
Congratulations TEAM :clap:** 
It is approved as you implemented all the changes requested by the previous TSE. It is working as expected. Now you can move to another project. All the Best.
Happy coding!!!

2020-09-17 13:57 UTC, merged